### ISSUE TITLE
Error when trying to run test

### ISSUE THREAD

**Issue by ephekt** [sandro/bench_press#2]
[13:20:13 miker@optisol-006 ~/optisol/src/rails/benchmarks] $ bench_press --publish tr_vs_gsub.rb
/usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/report.rb:59:in `heading': undefined method`name' for nil:NilClass (NoMethodError)
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/report.rb:63:in `runnable_heading'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/report.rb:20:in`to_s'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press.rb:95:in `puts'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press.rb:95
from /usr/local/bin/bench_press:19
/usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press.rb:43:in`date': undefined method `parse' for Time:Class (NoMethodError)
from /usr/local/share/optisol/src/rails/benchmarks/tr_vs_gsub.rb:8
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/cli.rb:77:in`load'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/cli.rb:77:in `measurable'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/cli.rb:66:in`perform_bench_press'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/lib/bench_press/cli.rb:55:in `run'
from /usr/local/lib/ruby/gems/1.8/gems/bench_press-0.3.0/bin/bench_press:4
from /usr/local/bin/bench_press:19:in`load'
from /usr/local/bin/bench_press:19

**Comment by sandro** [comment]
Just pushed a fix to master, will be in the 0.3.1 release
